spring:
  application.name: is-backend
  config:
    import: optional:classpath:application-local.yml
  datasource:
    url: ${DB_URL:jdbc:h2:mem:fallbackdb}
    username: ${DB_USERNAME:sa}
    password: ${DB_PASSWORD:}
  jpa:
    database-platform: ${DB_DIALECT:org.hibernate.dialect.H2Dialect}
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
server:
  port: 8080